FTAG4Content = [
"xAOD::EventInfo#*",
"xAOD::EventAuxInfo#*",
"xAOD::ElectronContainer#*",
"xAOD::ElectronAuxContainer#*",
"xAOD::MuonContainer#*",
"xAOD::MuonAuxContainer#*",
"xAOD::BTaggingContainer#*",
"xAOD::BTaggingAuxContainer#*",

"xAOD::JetContainer#AntiKt10LCTopoJets",
"xAOD::JetAuxContainer#AntiKt10LCTopoJetsAux.",
"xAOD::JetContainer#AntiKt10TruthJets",
"xAOD::JetAuxContainer#AntiKt10TruthJetsAux.",
"xAOD::JetContainer#AntiKt10TruthWZJets",
"xAOD::JetAuxContainer#AntiKt10TruthWZJetsAux.",

"xAOD::JetContainer#AntiKt4TruthJets",
"xAOD::JetAuxContainer#AntiKt4TruthJetsAux.",
"xAOD::JetContainer#AntiKt4TruthWZJets",
"xAOD::JetAuxContainer#AntiKt4TruthWZJetsAux.",
"xAOD::JetContainer#AntiKt4LCTopoJets",
"xAOD::JetAuxContainer#AntiKt4LCTopoJetsAux.",
"xAOD::JetContainer#AntiKt4EMTopoJets",
"xAOD::JetAuxContainer#AntiKt4EMTopoJetsAux.",

"xAOD::JetContainer#AntiKt3ZTrackJets",
"xAOD::JetAuxContainer#AntiKt3ZTrackJetsAux.",
"xAOD::JetContainer#AntiKt3PV0TrackJets",
"xAOD::JetAuxContainer#AntiKt3PV0TrackJetsAux.",
"xAOD::JetContainer#AntiKt4ZTrackJets",
"xAOD::JetAuxContainer#AntiKt4ZTrackJetsAux.",
"xAOD::JetContainer#AntiKt4PV0TrackJets",
"xAOD::JetAuxContainer#AntiKt4PV0TrackJetsAux.",

"xAOD::EventShape#*",
"xAOD::EventShapeAuxInfo#*",

"xAOD::TrackParticleContainer#CombinedMuonTrackParticles",
"xAOD::TrackParticleContainer#ExtrapolatedMuonTrackParticles",
"xAOD::TrackParticleContainer#GSFTrackParticles",
"xAOD::TrackParticleContainer#InDetTrackParticles",
"xAOD::TrackParticleContainer#InDetTrackParticlesForward",
"xAOD::TrackParticleAuxContainer#CombinedMuonTrackParticlesAux.",
"xAOD::TrackParticleAuxContainer#ExtrapolatedMuonTrackParticlesAux.",
"xAOD::TrackParticleAuxContainer#GSFTrackParticlesAux.",
"xAOD::TrackParticleAuxContainer#InDetTrackParticlesAux.",
"xAOD::TrackParticleAuxContainer#InDetTrackParticlesForwardAux.",

"xAOD::MissingETContainer#*",
"xAOD::MissingETAuxContainer#*",
"xAOD::MissingETComponentMap#*",
"xAOD::MissingETAuxComponentMap#*",

"xAOD::VertexContainer#PrimaryVertices",
"xAOD::VertexAuxContainer#PrimaryVerticesAux.",

"xAOD::TruthVertexContainer#*",
"xAOD::TruthVertexAuxContainer#*",
"xAOD::TruthParticleContainer#*",
"xAOD::TruthParticleAuxContainer#*",
"xAOD::TruthEventContainer#*",
"xAOD::TruthEventAuxContainer#*" ]
